outputFigureFolder = fullfile('E:\Data_p\ClosedLoopDataset\','manuscriptFigures');

% Load data saved by analyzeHealthyPtsPerformance__plots.m
% XLS table generated by writeResults2XLS.m
folderName = 'E:\Data_p\ClosedLoopDataset\BEHAV_LINK';
visualPAL_fig_data = load(fullfile(folderName,'dPrimeChange_dataset'),'visualPAL_fig_data');
visualPAL_fig_data = visualPAL_fig_data.visualPAL_fig_data;

PtCellIdx = visualPAL_fig_data.PtCellIdx;
couple_mat = visualPAL_fig_data.couple_mat;
couple_mat_PRUNED = visualPAL_fig_data.couple_mat_PRUNED ;
dprime_change_sleep = visualPAL_fig_data.dprime_change_sleep;
dprime_change_stim = visualPAL_fig_data.dprime_change_stim;
dprime_diff = visualPAL_fig_data.dprime_diff;
N_rec_diff = visualPAL_fig_data.N_rec_diff;
N_falsePos_diff = visualPAL_fig_data.N_falsePos_diff;

% 3 subgroups based on STIM targeting and anatomical area
% subGroup{1} - frontal_well_targeted_stim_pts
% subGroup{2} - posterior_well_targeted_stim_pts
% subGroup{3} - posterior_neg_stim_pts
[subGroup, cmap] = defineSubGroups_stimAnatomy();
global G_targeted; G_targeted = 1;
global G_targeted_diff_anatomy; G_targeted_diff_anatomy = 2;
global G_mixed; G_mixed = 3;
stim_color = cmap(1,:);
SHAM_NIGHT_COLOR = cmap(4,:);

color_i = [];
for ii = 1:size(couple_mat_PRUNED,1)
    for sg_i = 1:3
        if ismember(couple_mat_PRUNED(ii,3),subGroup{sg_i})
            color_i(ii) = sg_i;
        end
    end
end


color_i_full = [];
for ii = 1:size(couple_mat,1)
    for sg_i = 1:3
        if ismember(couple_mat(ii,3),subGroup{sg_i})
            color_i_full(ii) = sg_i;
        end
    end
end

%%

fsz = 10;
% STATS for manuscript
dirName = ('E:\Data_p\BEHAVIOR\memTestPatients_STATS');
saveName = fullfile(dirName, sprintf('visualPAL_fullResultTable'));
mm = matfile(saveName);

%%
fsz = 8;
figName = 'Fig1_g-h';
f = figure('Name', figName,'NumberTitle','off');
% Some WYSIWYG options:
set(gcf,'DefaultAxesFontSize',fsz);
set(gcf,'DefaultAxesFontName','arial');
set(gcf,'PaperUnits','centimeters','PaperPosition',[0.2 0.2 19 24]); % this size is the maximal to fit on an A4 paper when printing to PDF
set(gcf,'PaperOrientation','portrait');
set(gcf,'Units','centimeters','Position', get(gcf,'paperPosition')+[1 1 0 0]);
colormap('jet');

y_sz = 0.18;
pos1 = [0.11,0.55,0.1,y_sz];
pos2 = [0.33,0.55,0.1,y_sz];
pos3 = [0.55,0.55,0.1,y_sz];
pos4 = [0.75,0.55,0.1,y_sz];
pos5 = [0.11 0.1 0.1 y_sz];
pos6 = [0.55 0.1 0.1 y_sz];
pp = pos6; ii = 1;
pos6a = [pp(ii,1)+0.6*pp(ii,3),pp(ii,2)+0.8*pp(ii,4),pp(ii,3)/3,pp(ii,4)/3];
pos7 = [0.75 0.1 0.1 y_sz];
pp = pos7; ii = 1;
pos7a = [pp(ii,1)+0.6*pp(ii,3),pp(ii,2)+0.8*pp(ii,4),pp(ii,3)/3,pp(ii,4)/3];

%%%%%%%%%%%%%%%%
%% memory accuracy panels
axes('position',pos3)

LW = 2;
MS = 4;
[a,ind] = sort(color_i);
ind = fliplr(ind);

for ii = ind 
    disp(ii)
    hold all
    if color_i(ii)  == 3
        LW = 1.8;
    else
        LW = 2;
    end
    plot(2,dprime_change_stim(ii),...
        'o','markersize',MS,'markerfacecolor','k','markeredgecolor','k');
     plot(1:2,[dprime_change_sleep(ii),dprime_change_stim(ii)],...
        '-','LineWidth',LW,'color',cmap(color_i(ii),:));
     plot(1,dprime_change_sleep(ii),...
        'o','markersize',MS,'markerfacecolor','k','markeredgecolor','k');    
end

set(gca,'xtick',[1,2],'fontsize',fsz-2,'XTickLabel',...
    {'Sleep','Stimulation'},'XTickLabelRotation',45)
axis([0.5 2.5,-0.6 0.1])

set(gca,'fontsize',fsz)
set(gca,'ytick',[-0.6,0,0.1])
plot(get(gca,'xlim'),[0 0],'k--')
ystr{1} = 'Accuracy of recognition memory ';
ystr{2} = '(d'' morning - d'' evening)';

axes('position',pos4)
Y = dprime_diff(color_i == 1);
violinplot(1.1,Y','color',cmap(1,:))
hold all
Y = dprime_diff(color_i == 3);
violinplot(3.1,Y','color',cmap(3,:))
Y = dprime_diff(color_i == 2);
violinplot(2.1,Y','color',cmap(2,:))
alpha = 0.5;
% x_buf = rand([1,length(dprime_diff)])*.3;
% x_buf(3) = 0;
% x_buf(8) = 0;
% roll the dice once and keep the values
LW = 1;
% x_buf = [0.0885    0.0147         0    0.0686    0.0480    0.0138    0.0608         0    0.0915    0.1292 0.0885    0.0147 ];
  x_buf = [  0.0696    0.2871         0    0.1986    0.1513    0.0464    0.1832         0    0.1563    0.0361    0.0880    0.0510];

for ii = 1:length(dprime_diff)
    hold on
    % plot(color_i(ii)+x_buf(ii),dprime_diff(ii),'o','markersize',4,'linewidth',LW,'color',cmap(color_i(ii),:))
    plot(color_i(ii)+x_buf(ii),dprime_diff(ii),'o','markersize',4,'linewidth',LW,'color','k')
end

axis tight
hold on
set(gca,'fontsize',fsz,'xlim',[0.6,3.5])
plot(get(gca,'xlim'),[0 0],'k--')
clear str
str{1} = sprintf('Overnight memory accuracy enhancement ');
% ylabel(str);

set(gca,'xtick',[], 'ylim',[-0.5,0.5],'ytick',[-0.5,0,0.5])

a = gcf;
set(gcf,'renderer','zbuffer');
res = 400;
eval(['print ', [outputFigureFolder,'\',a.Name], ' -f', num2str(a.Number),sprintf(' -dtiff  -r%d',res), '-cmyk' ]); % adding r600 slows down this process significantly!
close(gcf)



